
 api1 Pulling 
 api2 Pulling 
 0bdf2c4d1714 Already exists 
 19f81082f6f0 Pulling fs layer 
 799df5177ae2 Pulling fs layer 
 66cd357cf7a1 Pulling fs layer 
 f2a664a2c5c7 Pulling fs layer 
 581fd715a4fb Pulling fs layer 
 997fcc85c431 Pulling fs layer 
 ed25f5495e76 Pulling fs layer 
 f2a664a2c5c7 Waiting 
 581fd715a4fb Waiting 
 997fcc85c431 Waiting 
 ed25f5495e76 Waiting 
 19f81082f6f0 Downloading [>                                                  ]  36.36kB/3.514MB
 799df5177ae2 Downloading [>                                                  ]  126.9kB/12.58MB
 0bdf2c4d1714 Already exists 
 66cd357cf7a1 Downloading [==================================================>]     250B/250B
 66cd357cf7a1 Verifying Checksum 
 66cd357cf7a1 Download complete 
 19f81082f6f0 Pulling fs layer 
 799df5177ae2 Pulling fs layer 
 66cd357cf7a1 Pulling fs layer 
 f2a664a2c5c7 Pulling fs layer 
 581fd715a4fb Pulling fs layer 
 997fcc85c431 Pulling fs layer 
 ed25f5495e76 Pulling fs layer 
 ed25f5495e76 Waiting 
 19f81082f6f0 Downloading [>                                                  ]  36.36kB/3.514MB
 799df5177ae2 Downloading [>                                                  ]  126.9kB/12.58MB
 66cd357cf7a1 Download complete 
 f2a664a2c5c7 Waiting 
 581fd715a4fb Waiting 
 997fcc85c431 Waiting 
 19f81082f6f0 Download complete 
 19f81082f6f0 Downloading [==================================================>]  3.514MB/3.514MB
 19f81082f6f0 Download complete 
 19f81082f6f0 Extracting [>                                                  ]  65.54kB/3.514MB
 19f81082f6f0 Extracting [>                                                  ]  65.54kB/3.514MB
 799df5177ae2 Downloading [===========================>                       ]   6.96MB/12.58MB
 799df5177ae2 Downloading [===========================>                       ]   6.96MB/12.58MB
 19f81082f6f0 Extracting [===============================>                   ]  2.228MB/3.514MB
 19f81082f6f0 Extracting [===============================>                   ]  2.228MB/3.514MB
 799df5177ae2 Downloading [===============================================>   ]  11.86MB/12.58MB
 799df5177ae2 Downloading [===============================================>   ]  11.86MB/12.58MB
 799df5177ae2 Verifying Checksum 
 799df5177ae2 Download complete 
 799df5177ae2 Verifying Checksum 
 799df5177ae2 Download complete 
 19f81082f6f0 Extracting [==================================================>]  3.514MB/3.514MB
 19f81082f6f0 Extracting [==================================================>]  3.514MB/3.514MB
 19f81082f6f0 Extracting [==================================================>]  3.514MB/3.514MB
 19f81082f6f0 Extracting [==================================================>]  3.514MB/3.514MB
 19f81082f6f0 Pull complete 
 19f81082f6f0 Pull complete 
 799df5177ae2 Extracting [>                                                  ]  131.1kB/12.58MB
 799df5177ae2 Extracting [>                                                  ]  131.1kB/12.58MB
 799df5177ae2 Extracting [======>                                            ]  1.704MB/12.58MB
 799df5177ae2 Extracting [======>                                            ]  1.704MB/12.58MB
 f2a664a2c5c7 Verifying Checksum 
 f2a664a2c5c7 Download complete 
 f2a664a2c5c7 Downloading [==================================================>]      93B/93B
 f2a664a2c5c7 Verifying Checksum 
 f2a664a2c5c7 Download complete 
 581fd715a4fb Downloading [==================================================>]     209B/209B
 581fd715a4fb Downloading [==================================================>]     209B/209B
 581fd715a4fb Verifying Checksum 
 581fd715a4fb Download complete 
 581fd715a4fb Verifying Checksum 
 581fd715a4fb Download complete 
 799df5177ae2 Extracting [=================>                                 ]  4.325MB/12.58MB
 799df5177ae2 Extracting [=================>                                 ]  4.325MB/12.58MB
 997fcc85c431 Downloading [>                                                  ]  176.8kB/17.47MB
 997fcc85c431 Downloading [>                                                  ]  176.8kB/17.47MB
 799df5177ae2 Extracting [============================>                      ]  7.078MB/12.58MB
 799df5177ae2 Extracting [============================>                      ]  7.078MB/12.58MB
 997fcc85c431 Downloading [======================>                            ]  7.924MB/17.47MB
 997fcc85c431 Downloading [======================>                            ]  7.924MB/17.47MB
 799df5177ae2 Extracting [==================================>                ]  8.782MB/12.58MB
 799df5177ae2 Extracting [==================================>                ]  8.782MB/12.58MB
 997fcc85c431 Verifying Checksum 
 997fcc85c431 Download complete 
 997fcc85c431 Verifying Checksum 
 997fcc85c431 Download complete 
 799df5177ae2 Extracting [=======================================>           ]  9.961MB/12.58MB
 799df5177ae2 Extracting [=======================================>           ]  9.961MB/12.58MB
 799df5177ae2 Extracting [=============================================>     ]   11.4MB/12.58MB
 799df5177ae2 Extracting [=============================================>     ]   11.4MB/12.58MB
 799df5177ae2 Extracting [==================================================>]  12.58MB/12.58MB
 799df5177ae2 Extracting [==================================================>]  12.58MB/12.58MB
 799df5177ae2 Extracting [==================================================>]  12.58MB/12.58MB
 799df5177ae2 Extracting [==================================================>]  12.58MB/12.58MB
 799df5177ae2 Pull complete 
 799df5177ae2 Pull complete 
 66cd357cf7a1 Extracting [==================================================>]     250B/250B
 66cd357cf7a1 Extracting [==================================================>]     250B/250B
 66cd357cf7a1 Extracting [==================================================>]     250B/250B
 66cd357cf7a1 Extracting [==================================================>]     250B/250B
 66cd357cf7a1 Pull complete 
 66cd357cf7a1 Pull complete 
 f2a664a2c5c7 Extracting [==================================================>]      93B/93B
 f2a664a2c5c7 Extracting [==================================================>]      93B/93B
 f2a664a2c5c7 Extracting [==================================================>]      93B/93B
 f2a664a2c5c7 Extracting [==================================================>]      93B/93B
 f2a664a2c5c7 Pull complete 
 f2a664a2c5c7 Pull complete 
 581fd715a4fb Extracting [==================================================>]     209B/209B
 581fd715a4fb Extracting [==================================================>]     209B/209B
 581fd715a4fb Extracting [==================================================>]     209B/209B
 581fd715a4fb Extracting [==================================================>]     209B/209B
 581fd715a4fb Pull complete 
 581fd715a4fb Pull complete 
 997fcc85c431 Extracting [>                                                  ]  196.6kB/17.47MB
 997fcc85c431 Extracting [>                                                  ]  196.6kB/17.47MB
 997fcc85c431 Extracting [======>                                            ]  2.359MB/17.47MB
 997fcc85c431 Extracting [======>                                            ]  2.359MB/17.47MB
 997fcc85c431 Extracting [===========>                                       ]  4.129MB/17.47MB
 997fcc85c431 Extracting [===========>                                       ]  4.129MB/17.47MB
 ed25f5495e76 Downloading [>                                                  ]  376.8kB/37.67MB
 ed25f5495e76 Downloading [>                                                  ]  376.8kB/37.67MB
 997fcc85c431 Extracting [==============>                                    ]  5.112MB/17.47MB
 997fcc85c431 Extracting [==============>                                    ]  5.112MB/17.47MB
 ed25f5495e76 Downloading [=========>                                         ]   7.27MB/37.67MB
 ed25f5495e76 Downloading [=========>                                         ]   7.27MB/37.67MB
 997fcc85c431 Extracting [==================>                                ]  6.488MB/17.47MB
 997fcc85c431 Extracting [==================>                                ]  6.488MB/17.47MB
 ed25f5495e76 Downloading [====================>                              ]  15.62MB/37.67MB
 ed25f5495e76 Downloading [====================>                              ]  15.62MB/37.67MB
 997fcc85c431 Extracting [======================>                            ]  7.864MB/17.47MB
 997fcc85c431 Extracting [======================>                            ]  7.864MB/17.47MB
 ed25f5495e76 Downloading [=================================>                 ]   25.5MB/37.67MB
 ed25f5495e76 Downloading [=================================>                 ]   25.5MB/37.67MB
 997fcc85c431 Extracting [=========================>                         ]  9.044MB/17.47MB
 997fcc85c431 Extracting [=========================>                         ]  9.044MB/17.47MB
 ed25f5495e76 Downloading [==============================================>    ]  35.01MB/37.67MB
 ed25f5495e76 Downloading [==============================================>    ]  35.01MB/37.67MB
 ed25f5495e76 Verifying Checksum 
 ed25f5495e76 Download complete 
 ed25f5495e76 Verifying Checksum 
 ed25f5495e76 Download complete 
 997fcc85c431 Extracting [===================================>               ]  12.39MB/17.47MB
 997fcc85c431 Extracting [===================================>               ]  12.39MB/17.47MB
 997fcc85c431 Extracting [==============================================>    ]  16.32MB/17.47MB
 997fcc85c431 Extracting [==============================================>    ]  16.32MB/17.47MB
 997fcc85c431 Extracting [==================================================>]  17.47MB/17.47MB
 997fcc85c431 Extracting [==================================================>]  17.47MB/17.47MB
 997fcc85c431 Pull complete 
 997fcc85c431 Pull complete 
 ed25f5495e76 Extracting [>                                                  ]  393.2kB/37.67MB
 ed25f5495e76 Extracting [>                                                  ]  393.2kB/37.67MB
 ed25f5495e76 Extracting [===>                                               ]  2.359MB/37.67MB
 ed25f5495e76 Extracting [===>                                               ]  2.359MB/37.67MB
 ed25f5495e76 Extracting [=====>                                             ]  3.932MB/37.67MB
 ed25f5495e76 Extracting [=====>                                             ]  3.932MB/37.67MB
 ed25f5495e76 Extracting [============>                                      ]  9.044MB/37.67MB
 ed25f5495e76 Extracting [============>                                      ]  9.044MB/37.67MB
 ed25f5495e76 Extracting [==============>                                    ]  10.62MB/37.67MB
 ed25f5495e76 Extracting [==============>                                    ]  10.62MB/37.67MB
 ed25f5495e76 Extracting [================>                                  ]  12.19MB/37.67MB
 ed25f5495e76 Extracting [================>                                  ]  12.19MB/37.67MB
 ed25f5495e76 Extracting [================>                                  ]  12.58MB/37.67MB
 ed25f5495e76 Extracting [================>                                  ]  12.58MB/37.67MB
 ed25f5495e76 Extracting [==================>                                ]  13.76MB/37.67MB
 ed25f5495e76 Extracting [==================>                                ]  13.76MB/37.67MB
 ed25f5495e76 Extracting [====================>                              ]  15.73MB/37.67MB
 ed25f5495e76 Extracting [====================>                              ]  15.73MB/37.67MB
 ed25f5495e76 Extracting [=======================>                           ]  17.69MB/37.67MB
 ed25f5495e76 Extracting [=======================>                           ]  17.69MB/37.67MB
 ed25f5495e76 Extracting [=========================>                         ]  19.27MB/37.67MB
 ed25f5495e76 Extracting [=========================>                         ]  19.27MB/37.67MB
 ed25f5495e76 Extracting [=============================>                     ]  22.41MB/37.67MB
 ed25f5495e76 Extracting [=============================>                     ]  22.41MB/37.67MB
 ed25f5495e76 Extracting [================================>                  ]  24.38MB/37.67MB
 ed25f5495e76 Extracting [================================>                  ]  24.38MB/37.67MB
 ed25f5495e76 Extracting [=================================>                 ]  25.56MB/37.67MB
 ed25f5495e76 Extracting [=================================>                 ]  25.56MB/37.67MB
 ed25f5495e76 Extracting [====================================>              ]  27.53MB/37.67MB
 ed25f5495e76 Extracting [====================================>              ]  27.53MB/37.67MB
 ed25f5495e76 Extracting [========================================>          ]  30.28MB/37.67MB
 ed25f5495e76 Extracting [========================================>          ]  30.28MB/37.67MB
 ed25f5495e76 Extracting [===========================================>       ]  32.64MB/37.67MB
 ed25f5495e76 Extracting [===========================================>       ]  32.64MB/37.67MB
 ed25f5495e76 Extracting [==============================================>    ]  35.39MB/37.67MB
 ed25f5495e76 Extracting [==============================================>    ]  35.39MB/37.67MB
 ed25f5495e76 Extracting [==================================================>]  37.67MB/37.67MB
 ed25f5495e76 Extracting [==================================================>]  37.67MB/37.67MB
 ed25f5495e76 Pull complete 
 ed25f5495e76 Pull complete 
 api1 Pulled 
 api2 Pulled 
 Network pedrohsb-python_backend  Creating
 Network pedrohsb-python_backend  Created
 Container pedrohsb-python-api2-1  Creating
 Container pedrohsb-python-api1-1  Creating
 Container pedrohsb-python-api2-1  Created
 Container pedrohsb-python-api1-1  Created
 Container nginx1  Creating
 Container nginx1  Created
Attaching to nginx1, api1-1, api2-1
nginx1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx1  | /docker-entrypoint.sh: Configuration complete; ready for start up
api1-1  | INFO:     Started server process [1]
api1-1  | INFO:     Waiting for application startup.
api1-1  | INFO:     Application startup complete.
api1-1  | INFO:     Uvicorn running on http://0.0.0.0:9999 (Press CTRL+C to quit)
api2-1  | INFO:     Started server process [1]
api2-1  | INFO:     Waiting for application startup.
api2-1  | INFO:     Application startup complete.
api2-1  | INFO:     Uvicorn running on http://0.0.0.0:9999 (Press CTRL+C to quit)
api1-1  | ERROR:    Exception in ASGI application
api1-1  | Traceback (most recent call last):
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
api1-1  |     yield
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
api1-1  |     resp = await self._pool.handle_async_request(req)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 207, in handle_async_request
api1-1  |     raise UnsupportedProtocol(
api1-1  |         "Request URL is missing an 'http://' or 'https://' protocol."
api1-1  |     )
api1-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api1-1  | 
api1-1  | The above exception was the direct cause of the following exception:
api1-1  | 
api1-1  | Traceback (most recent call last):
api1-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
api1-1  |     result = await app(  # type: ignore[func-returns-value]
api1-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |         self.scope, self.receive, self.send
api1-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
api1-1  |     return await self.app(scope, receive, send)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
api1-1  |     await super().__call__(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
api1-1  |     await self.middleware_stack(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 186, in __call__
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
api1-1  |     await self.app(scope, receive, _send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
api1-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api1-1  |     await app(scope, receive, sender)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 716, in __call__
api1-1  |     await self.middleware_stack(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 736, in app
api1-1  |     await route.handle(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 290, in handle
api1-1  |     await self.app(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 78, in app
api1-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api1-1  |     await app(scope, receive, sender)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 75, in app
api1-1  |     response = await f(request)
api1-1  |                ^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 302, in app
api1-1  |     raw_response = await run_endpoint_function(
api1-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<3 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
api1-1  |     return await dependant.call(**values)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/app/app/apis/main.py", line 87, in payments_summary
api1-1  |     res = await client.get(
api1-1  |           ^^^^^^^^^^^^^^^^^
api1-1  |     ...<2 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1768, in get
api1-1  |     return await self.request(
api1-1  |            ^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<9 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1540, in request
api1-1  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1629, in send
api1-1  |     response = await self._send_handling_auth(
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<4 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
api1-1  |     response = await self._send_handling_redirects(
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<3 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
api1-1  |     response = await self._send_single_request(request)
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1730, in _send_single_request
api1-1  |     response = await transport.handle_async_request(request)
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 393, in handle_async_request
api1-1  |     with map_httpcore_exceptions():
api1-1  |          ~~~~~~~~~~~~~~~~~~~~~~~^^
api1-1  |   File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
api1-1  |     self.gen.throw(value)
api1-1  |     ~~~~~~~~~~~~~~^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
api1-1  |     raise mapped_exc(message) from exc
api1-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api2-1  | ERROR:    Exception in ASGI application
api2-1  | Traceback (most recent call last):
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
api2-1  |     yield
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
api2-1  |     resp = await self._pool.handle_async_request(req)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 207, in handle_async_request
api2-1  |     raise UnsupportedProtocol(
api2-1  |         "Request URL is missing an 'http://' or 'https://' protocol."
api2-1  |     )
api2-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api2-1  | 
api2-1  | The above exception was the direct cause of the following exception:
api2-1  | 
api2-1  | Traceback (most recent call last):
api2-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
api2-1  |     result = await app(  # type: ignore[func-returns-value]
api2-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |         self.scope, self.receive, self.send
api2-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
api2-1  |     return await self.app(scope, receive, send)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
api2-1  |     await super().__call__(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
api2-1  |     await self.middleware_stack(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 186, in __call__
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
api2-1  |     await self.app(scope, receive, _send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
api2-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api2-1  |     await app(scope, receive, sender)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 716, in __call__
api2-1  |     await self.middleware_stack(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 736, in app
api2-1  |     await route.handle(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 290, in handle
api2-1  |     await self.app(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 78, in app
api2-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api2-1  |     await app(scope, receive, sender)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 75, in app
api2-1  |     response = await f(request)
api2-1  |                ^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 302, in app
api2-1  |     raw_response = await run_endpoint_function(
api2-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<3 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
api2-1  |     return await dependant.call(**values)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/app/app/apis/main.py", line 87, in payments_summary
api2-1  |     res = await client.get(
api2-1  |           ^^^^^^^^^^^^^^^^^
api2-1  |     ...<2 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1768, in get
api2-1  |     return await self.request(
api2-1  |            ^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<9 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1540, in request
api2-1  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1629, in send
api2-1  |     response = await self._send_handling_auth(
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<4 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
api2-1  |     response = await self._send_handling_redirects(
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<3 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
api2-1  |     response = await self._send_single_request(request)
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1730, in _send_single_request
api2-1  |     response = await transport.handle_async_request(request)
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 393, in handle_async_request
api2-1  |     with map_httpcore_exceptions():
api2-1  |          ~~~~~~~~~~~~~~~~~~~~~~~^^
api2-1  |   File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
api2-1  |     self.gen.throw(value)
api2-1  |     ~~~~~~~~~~~~~~^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
api2-1  |     raise mapped_exc(message) from exc
api2-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api1-1  | ERROR:    Exception in ASGI application
api1-1  | Traceback (most recent call last):
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
api1-1  |     yield
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
api1-1  |     resp = await self._pool.handle_async_request(req)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 207, in handle_async_request
api1-1  |     raise UnsupportedProtocol(
api1-1  |         "Request URL is missing an 'http://' or 'https://' protocol."
api1-1  |     )
api1-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api1-1  | 
api1-1  | The above exception was the direct cause of the following exception:
api1-1  | 
api1-1  | Traceback (most recent call last):
api1-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
api1-1  |     result = await app(  # type: ignore[func-returns-value]
api1-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |         self.scope, self.receive, self.send
api1-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
api1-1  |     return await self.app(scope, receive, send)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
api1-1  |     await super().__call__(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
api1-1  |     await self.middleware_stack(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 186, in __call__
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
api1-1  |     await self.app(scope, receive, _send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
api1-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api1-1  |     await app(scope, receive, sender)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 716, in __call__
api1-1  |     await self.middleware_stack(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 736, in app
api1-1  |     await route.handle(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 290, in handle
api1-1  |     await self.app(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 78, in app
api1-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api1-1  |     await app(scope, receive, sender)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 75, in app
api1-1  |     response = await f(request)
api1-1  |                ^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 302, in app
api1-1  |     raw_response = await run_endpoint_function(
api1-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<3 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
api1-1  |     return await dependant.call(**values)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/app/app/apis/main.py", line 87, in payments_summary
api1-1  |     res = await client.get(
api1-1  |           ^^^^^^^^^^^^^^^^^
api1-1  |     ...<2 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1768, in get
api1-1  |     return await self.request(
api1-1  |            ^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<9 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1540, in request
api1-1  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1629, in send
api1-1  |     response = await self._send_handling_auth(
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<4 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
api1-1  |     response = await self._send_handling_redirects(
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<3 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
api1-1  |     response = await self._send_single_request(request)
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1730, in _send_single_request
api1-1  |     response = await transport.handle_async_request(request)
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 393, in handle_async_request
api1-1  |     with map_httpcore_exceptions():
api1-1  |          ~~~~~~~~~~~~~~~~~~~~~~~^^
api1-1  |   File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
api1-1  |     self.gen.throw(value)
api1-1  |     ~~~~~~~~~~~~~~^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
api1-1  |     raise mapped_exc(message) from exc
api1-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api2-1  | ERROR:    Exception in ASGI application
api2-1  | Traceback (most recent call last):
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
api2-1  |     yield
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
api2-1  |     resp = await self._pool.handle_async_request(req)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 207, in handle_async_request
api2-1  |     raise UnsupportedProtocol(
api2-1  |         "Request URL is missing an 'http://' or 'https://' protocol."
api2-1  |     )
api2-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api2-1  | 
api2-1  | The above exception was the direct cause of the following exception:
api2-1  | 
api2-1  | Traceback (most recent call last):
api2-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
api2-1  |     result = await app(  # type: ignore[func-returns-value]
api2-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |         self.scope, self.receive, self.send
api2-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
api2-1  |     return await self.app(scope, receive, send)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
api2-1  |     await super().__call__(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
api2-1  |     await self.middleware_stack(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 186, in __call__
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
api2-1  |     await self.app(scope, receive, _send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
api2-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api2-1  |     await app(scope, receive, sender)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 716, in __call__
api2-1  |     await self.middleware_stack(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 736, in app
api2-1  |     await route.handle(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 290, in handle
api2-1  |     await self.app(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 78, in app
api2-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api2-1  |     await app(scope, receive, sender)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 75, in app
api2-1  |     response = await f(request)
api2-1  |                ^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 302, in app
api2-1  |     raw_response = await run_endpoint_function(
api2-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<3 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
api2-1  |     return await dependant.call(**values)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/app/app/apis/main.py", line 87, in payments_summary
api2-1  |     res = await client.get(
api2-1  |           ^^^^^^^^^^^^^^^^^
api2-1  |     ...<2 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1768, in get
api2-1  |     return await self.request(
api2-1  |            ^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<9 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1540, in request
api2-1  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1629, in send
api2-1  |     response = await self._send_handling_auth(
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<4 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
api2-1  |     response = await self._send_handling_redirects(
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<3 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
api2-1  |     response = await self._send_single_request(request)
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1730, in _send_single_request
api2-1  |     response = await transport.handle_async_request(request)
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 393, in handle_async_request
api2-1  |     with map_httpcore_exceptions():
api2-1  |          ~~~~~~~~~~~~~~~~~~~~~~~^^
api2-1  |   File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
api2-1  |     self.gen.throw(value)
api2-1  |     ~~~~~~~~~~~~~~^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
api2-1  |     raise mapped_exc(message) from exc
api2-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api1-1  | ERROR:    Exception in ASGI application
api1-1  | Traceback (most recent call last):
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
api1-1  |     yield
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
api1-1  |     resp = await self._pool.handle_async_request(req)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 207, in handle_async_request
api1-1  |     raise UnsupportedProtocol(
api1-1  |         "Request URL is missing an 'http://' or 'https://' protocol."
api1-1  |     )
api1-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api1-1  | 
api1-1  | The above exception was the direct cause of the following exception:
api1-1  | 
api1-1  | Traceback (most recent call last):
api1-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
api1-1  |     result = await app(  # type: ignore[func-returns-value]
api1-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |         self.scope, self.receive, self.send
api1-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
api1-1  |     return await self.app(scope, receive, send)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
api1-1  |     await super().__call__(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
api1-1  |     await self.middleware_stack(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 186, in __call__
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
api1-1  |     await self.app(scope, receive, _send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
api1-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api1-1  |     await app(scope, receive, sender)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 716, in __call__
api1-1  |     await self.middleware_stack(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 736, in app
api1-1  |     await route.handle(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 290, in handle
api1-1  |     await self.app(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 78, in app
api1-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api1-1  |     await app(scope, receive, sender)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 75, in app
api1-1  |     response = await f(request)
api1-1  |                ^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 302, in app
api1-1  |     raw_response = await run_endpoint_function(
api1-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<3 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
api1-1  |     return await dependant.call(**values)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/app/app/apis/main.py", line 87, in payments_summary
api1-1  |     res = await client.get(
api1-1  |           ^^^^^^^^^^^^^^^^^
api1-1  |     ...<2 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1768, in get
api1-1  |     return await self.request(
api1-1  |            ^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<9 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1540, in request
api1-1  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1629, in send
api1-1  |     response = await self._send_handling_auth(
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<4 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
api1-1  |     response = await self._send_handling_redirects(
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<3 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
api1-1  |     response = await self._send_single_request(request)
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1730, in _send_single_request
api1-1  |     response = await transport.handle_async_request(request)
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 393, in handle_async_request
api1-1  |     with map_httpcore_exceptions():
api1-1  |          ~~~~~~~~~~~~~~~~~~~~~~~^^
api1-1  |   File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
api1-1  |     self.gen.throw(value)
api1-1  |     ~~~~~~~~~~~~~~^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
api1-1  |     raise mapped_exc(message) from exc
api1-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api2-1  | ERROR:    Exception in ASGI application
api2-1  | Traceback (most recent call last):
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
api2-1  |     yield
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
api2-1  |     resp = await self._pool.handle_async_request(req)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 207, in handle_async_request
api2-1  |     raise UnsupportedProtocol(
api2-1  |         "Request URL is missing an 'http://' or 'https://' protocol."
api2-1  |     )
api2-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api2-1  | 
api2-1  | The above exception was the direct cause of the following exception:
api2-1  | 
api2-1  | Traceback (most recent call last):
api2-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
api2-1  |     result = await app(  # type: ignore[func-returns-value]
api2-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |         self.scope, self.receive, self.send
api2-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
api2-1  |     return await self.app(scope, receive, send)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
api2-1  |     await super().__call__(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
api2-1  |     await self.middleware_stack(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 186, in __call__
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
api2-1  |     await self.app(scope, receive, _send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
api2-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api2-1  |     await app(scope, receive, sender)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 716, in __call__
api2-1  |     await self.middleware_stack(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 736, in app
api2-1  |     await route.handle(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 290, in handle
api2-1  |     await self.app(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 78, in app
api2-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api2-1  |     await app(scope, receive, sender)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 75, in app
api2-1  |     response = await f(request)
api2-1  |                ^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 302, in app
api2-1  |     raw_response = await run_endpoint_function(
api2-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<3 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
api2-1  |     return await dependant.call(**values)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/app/app/apis/main.py", line 87, in payments_summary
api2-1  |     res = await client.get(
api2-1  |           ^^^^^^^^^^^^^^^^^
api2-1  |     ...<2 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1768, in get
api2-1  |     return await self.request(
api2-1  |            ^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<9 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1540, in request
api2-1  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1629, in send
api2-1  |     response = await self._send_handling_auth(
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<4 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
api2-1  |     response = await self._send_handling_redirects(
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<3 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
api2-1  |     response = await self._send_single_request(request)
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1730, in _send_single_request
api2-1  |     response = await transport.handle_async_request(request)
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 393, in handle_async_request
api2-1  |     with map_httpcore_exceptions():
api2-1  |          ~~~~~~~~~~~~~~~~~~~~~~~^^
api2-1  |   File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
api2-1  |     self.gen.throw(value)
api2-1  |     ~~~~~~~~~~~~~~^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
api2-1  |     raise mapped_exc(message) from exc
api2-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api1-1  | ERROR:    Exception in ASGI application
api1-1  | Traceback (most recent call last):
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
api1-1  |     yield
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
api1-1  |     resp = await self._pool.handle_async_request(req)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 207, in handle_async_request
api1-1  |     raise UnsupportedProtocol(
api1-1  |         "Request URL is missing an 'http://' or 'https://' protocol."
api1-1  |     )
api1-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api1-1  | 
api1-1  | The above exception was the direct cause of the following exception:
api1-1  | 
api1-1  | Traceback (most recent call last):
api1-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
api1-1  |     result = await app(  # type: ignore[func-returns-value]
api1-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |         self.scope, self.receive, self.send
api1-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
api1-1  |     return await self.app(scope, receive, send)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
api1-1  |     await super().__call__(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
api1-1  |     await self.middleware_stack(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 186, in __call__
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
api1-1  |     await self.app(scope, receive, _send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
api1-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api1-1  |     await app(scope, receive, sender)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 716, in __call__
api1-1  |     await self.middleware_stack(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 736, in app
api1-1  |     await route.handle(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 290, in handle
api1-1  |     await self.app(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 78, in app
api1-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api1-1  |     await app(scope, receive, sender)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 75, in app
api1-1  |     response = await f(request)
api1-1  |                ^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 302, in app
api1-1  |     raw_response = await run_endpoint_function(
api1-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<3 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
api1-1  |     return await dependant.call(**values)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/app/app/apis/main.py", line 87, in payments_summary
api1-1  |     res = await client.get(
api1-1  |           ^^^^^^^^^^^^^^^^^
api1-1  |     ...<2 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1768, in get
api1-1  |     return await self.request(
api1-1  |            ^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<9 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1540, in request
api1-1  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1629, in send
api1-1  |     response = await self._send_handling_auth(
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<4 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
api1-1  |     response = await self._send_handling_redirects(
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<3 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
api1-1  |     response = await self._send_single_request(request)
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1730, in _send_single_request
api1-1  |     response = await transport.handle_async_request(request)
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 393, in handle_async_request
api1-1  |     with map_httpcore_exceptions():
api1-1  |          ~~~~~~~~~~~~~~~~~~~~~~~^^
api1-1  |   File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
api1-1  |     self.gen.throw(value)
api1-1  |     ~~~~~~~~~~~~~~^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
api1-1  |     raise mapped_exc(message) from exc
api1-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api2-1  | ERROR:    Exception in ASGI application
api2-1  | Traceback (most recent call last):
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
api2-1  |     yield
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
api2-1  |     resp = await self._pool.handle_async_request(req)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 207, in handle_async_request
api2-1  |     raise UnsupportedProtocol(
api2-1  |         "Request URL is missing an 'http://' or 'https://' protocol."
api2-1  |     )
api2-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api2-1  | 
api2-1  | The above exception was the direct cause of the following exception:
api2-1  | 
api2-1  | Traceback (most recent call last):
api2-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
api2-1  |     result = await app(  # type: ignore[func-returns-value]
api2-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |         self.scope, self.receive, self.send
api2-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
api2-1  |     return await self.app(scope, receive, send)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
api2-1  |     await super().__call__(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
api2-1  |     await self.middleware_stack(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 186, in __call__
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
api2-1  |     await self.app(scope, receive, _send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
api2-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api2-1  |     await app(scope, receive, sender)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 716, in __call__
api2-1  |     await self.middleware_stack(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 736, in app
api2-1  |     await route.handle(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 290, in handle
api2-1  |     await self.app(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 78, in app
api2-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api2-1  |     await app(scope, receive, sender)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 75, in app
api2-1  |     response = await f(request)
api2-1  |                ^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 302, in app
api2-1  |     raw_response = await run_endpoint_function(
api2-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<3 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
api2-1  |     return await dependant.call(**values)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/app/app/apis/main.py", line 87, in payments_summary
api2-1  |     res = await client.get(
api2-1  |           ^^^^^^^^^^^^^^^^^
api2-1  |     ...<2 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1768, in get
api2-1  |     return await self.request(
api2-1  |            ^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<9 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1540, in request
api2-1  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1629, in send
api2-1  |     response = await self._send_handling_auth(
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<4 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
api2-1  |     response = await self._send_handling_redirects(
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<3 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
api2-1  |     response = await self._send_single_request(request)
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1730, in _send_single_request
api2-1  |     response = await transport.handle_async_request(request)
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 393, in handle_async_request
api2-1  |     with map_httpcore_exceptions():
api2-1  |          ~~~~~~~~~~~~~~~~~~~~~~~^^
api2-1  |   File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
api2-1  |     self.gen.throw(value)
api2-1  |     ~~~~~~~~~~~~~~^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
api2-1  |     raise mapped_exc(message) from exc
api2-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api1-1  | ERROR:    Exception in ASGI application
api1-1  | Traceback (most recent call last):
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
api1-1  |     yield
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
api1-1  |     resp = await self._pool.handle_async_request(req)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 207, in handle_async_request
api1-1  |     raise UnsupportedProtocol(
api1-1  |         "Request URL is missing an 'http://' or 'https://' protocol."
api1-1  |     )
api1-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api1-1  | 
api1-1  | The above exception was the direct cause of the following exception:
api1-1  | 
api1-1  | Traceback (most recent call last):
api1-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
api1-1  |     result = await app(  # type: ignore[func-returns-value]
api1-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |         self.scope, self.receive, self.send
api1-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
api1-1  |     return await self.app(scope, receive, send)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
api1-1  |     await super().__call__(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
api1-1  |     await self.middleware_stack(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 186, in __call__
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
api1-1  |     await self.app(scope, receive, _send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
api1-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api1-1  |     await app(scope, receive, sender)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 716, in __call__
api1-1  |     await self.middleware_stack(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 736, in app
api1-1  |     await route.handle(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 290, in handle
api1-1  |     await self.app(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 78, in app
api1-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api1-1  |     await app(scope, receive, sender)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 75, in app
api1-1  |     response = await f(request)
api1-1  |                ^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 302, in app
api1-1  |     raw_response = await run_endpoint_function(
api1-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<3 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
api1-1  |     return await dependant.call(**values)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/app/app/apis/main.py", line 87, in payments_summary
api1-1  |     res = await client.get(
api1-1  |           ^^^^^^^^^^^^^^^^^
api1-1  |     ...<2 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1768, in get
api1-1  |     return await self.request(
api1-1  |            ^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<9 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1540, in request
api1-1  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1629, in send
api1-1  |     response = await self._send_handling_auth(
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<4 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
api1-1  |     response = await self._send_handling_redirects(
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<3 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
api1-1  |     response = await self._send_single_request(request)
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1730, in _send_single_request
api1-1  |     response = await transport.handle_async_request(request)
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 393, in handle_async_request
api1-1  |     with map_httpcore_exceptions():
api1-1  |          ~~~~~~~~~~~~~~~~~~~~~~~^^
api1-1  |   File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
api1-1  |     self.gen.throw(value)
api1-1  |     ~~~~~~~~~~~~~~^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
api1-1  |     raise mapped_exc(message) from exc
api1-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api2-1  | ERROR:    Exception in ASGI application
api2-1  | Traceback (most recent call last):
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
api2-1  |     yield
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
api2-1  |     resp = await self._pool.handle_async_request(req)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 207, in handle_async_request
api2-1  |     raise UnsupportedProtocol(
api2-1  |         "Request URL is missing an 'http://' or 'https://' protocol."
api2-1  |     )
api2-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api2-1  | 
api2-1  | The above exception was the direct cause of the following exception:
api2-1  | 
api2-1  | Traceback (most recent call last):
api2-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
api2-1  |     result = await app(  # type: ignore[func-returns-value]
api2-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |         self.scope, self.receive, self.send
api2-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
api2-1  |     return await self.app(scope, receive, send)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
api2-1  |     await super().__call__(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
api2-1  |     await self.middleware_stack(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 186, in __call__
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
api2-1  |     await self.app(scope, receive, _send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
api2-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api2-1  |     await app(scope, receive, sender)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 716, in __call__
api2-1  |     await self.middleware_stack(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 736, in app
api2-1  |     await route.handle(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 290, in handle
api2-1  |     await self.app(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 78, in app
api2-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api2-1  |     await app(scope, receive, sender)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 75, in app
api2-1  |     response = await f(request)
api2-1  |                ^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 302, in app
api2-1  |     raw_response = await run_endpoint_function(
api2-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<3 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
api2-1  |     return await dependant.call(**values)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/app/app/apis/main.py", line 87, in payments_summary
api2-1  |     res = await client.get(
api2-1  |           ^^^^^^^^^^^^^^^^^
api2-1  |     ...<2 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1768, in get
api2-1  |     return await self.request(
api2-1  |            ^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<9 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1540, in request
api2-1  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1629, in send
api2-1  |     response = await self._send_handling_auth(
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<4 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
api2-1  |     response = await self._send_handling_redirects(
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<3 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
api2-1  |     response = await self._send_single_request(request)
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1730, in _send_single_request
api2-1  |     response = await transport.handle_async_request(request)
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 393, in handle_async_request
api2-1  |     with map_httpcore_exceptions():
api2-1  |          ~~~~~~~~~~~~~~~~~~~~~~~^^
api2-1  |   File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
api2-1  |     self.gen.throw(value)
api2-1  |     ~~~~~~~~~~~~~~^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
api2-1  |     raise mapped_exc(message) from exc
api2-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api1-1  | ERROR:    Exception in ASGI application
api1-1  | Traceback (most recent call last):
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
api1-1  |     yield
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
api1-1  |     resp = await self._pool.handle_async_request(req)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 207, in handle_async_request
api1-1  |     raise UnsupportedProtocol(
api1-1  |         "Request URL is missing an 'http://' or 'https://' protocol."
api1-1  |     )
api1-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api1-1  | 
api1-1  | The above exception was the direct cause of the following exception:
api1-1  | 
api1-1  | Traceback (most recent call last):
api1-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
api1-1  |     result = await app(  # type: ignore[func-returns-value]
api1-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |         self.scope, self.receive, self.send
api1-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
api1-1  |     return await self.app(scope, receive, send)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
api1-1  |     await super().__call__(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
api1-1  |     await self.middleware_stack(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 186, in __call__
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
api1-1  |     await self.app(scope, receive, _send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
api1-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api1-1  |     await app(scope, receive, sender)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 716, in __call__
api1-1  |     await self.middleware_stack(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 736, in app
api1-1  |     await route.handle(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 290, in handle
api1-1  |     await self.app(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 78, in app
api1-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api1-1  |     raise exc
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api1-1  |     await app(scope, receive, sender)
api1-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 75, in app
api1-1  |     response = await f(request)
api1-1  |                ^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 302, in app
api1-1  |     raw_response = await run_endpoint_function(
api1-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<3 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
api1-1  |     return await dependant.call(**values)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/app/app/apis/main.py", line 87, in payments_summary
api1-1  |     res = await client.get(
api1-1  |           ^^^^^^^^^^^^^^^^^
api1-1  |     ...<2 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1768, in get
api1-1  |     return await self.request(
api1-1  |            ^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<9 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1540, in request
api1-1  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
api1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1629, in send
api1-1  |     response = await self._send_handling_auth(
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<4 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
api1-1  |     response = await self._send_handling_redirects(
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |     ...<3 lines>...
api1-1  |     )
api1-1  |     ^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
api1-1  |     response = await self._send_single_request(request)
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1730, in _send_single_request
api1-1  |     response = await transport.handle_async_request(request)
api1-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 393, in handle_async_request
api1-1  |     with map_httpcore_exceptions():
api1-1  |          ~~~~~~~~~~~~~~~~~~~~~~~^^
api1-1  |   File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
api1-1  |     self.gen.throw(value)
api1-1  |     ~~~~~~~~~~~~~~^^^^^^^
api1-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
api1-1  |     raise mapped_exc(message) from exc
api1-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api2-1  | ERROR:    Exception in ASGI application
api2-1  | Traceback (most recent call last):
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
api2-1  |     yield
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
api2-1  |     resp = await self._pool.handle_async_request(req)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 207, in handle_async_request
api2-1  |     raise UnsupportedProtocol(
api2-1  |         "Request URL is missing an 'http://' or 'https://' protocol."
api2-1  |     )
api2-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
api2-1  | 
api2-1  | The above exception was the direct cause of the following exception:
api2-1  | 
api2-1  | Traceback (most recent call last):
api2-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
api2-1  |     result = await app(  # type: ignore[func-returns-value]
api2-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |         self.scope, self.receive, self.send
api2-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
api2-1  |     return await self.app(scope, receive, send)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
api2-1  |     await super().__call__(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
api2-1  |     await self.middleware_stack(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 186, in __call__
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
api2-1  |     await self.app(scope, receive, _send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
api2-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api2-1  |     await app(scope, receive, sender)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 716, in __call__
api2-1  |     await self.middleware_stack(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 736, in app
api2-1  |     await route.handle(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 290, in handle
api2-1  |     await self.app(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 78, in app
api2-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
api2-1  |     raise exc
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
api2-1  |     await app(scope, receive, sender)
api2-1  |   File "/usr/local/lib/python3.13/site-packages/starlette/routing.py", line 75, in app
api2-1  |     response = await f(request)
api2-1  |                ^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 302, in app
api2-1  |     raw_response = await run_endpoint_function(
api2-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<3 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
api2-1  |     return await dependant.call(**values)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/app/app/apis/main.py", line 87, in payments_summary
api2-1  |     res = await client.get(
api2-1  |           ^^^^^^^^^^^^^^^^^
api2-1  |     ...<2 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1768, in get
api2-1  |     return await self.request(
api2-1  |            ^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<9 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1540, in request
api2-1  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
api2-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1629, in send
api2-1  |     response = await self._send_handling_auth(
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<4 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
api2-1  |     response = await self._send_handling_redirects(
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |     ...<3 lines>...
api2-1  |     )
api2-1  |     ^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
api2-1  |     response = await self._send_single_request(request)
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1730, in _send_single_request
api2-1  |     response = await transport.handle_async_request(request)
api2-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 393, in handle_async_request
api2-1  |     with map_httpcore_exceptions():
api2-1  |          ~~~~~~~~~~~~~~~~~~~~~~~^^
api2-1  |   File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
api2-1  |     self.gen.throw(value)
api2-1  |     ~~~~~~~~~~~~~~^^^^^^^
api2-1  |   File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
api2-1  |     raise mapped_exc(message) from exc
api2-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
[Knginx1 exited with code 0
api2-1  | INFO:     Shutting down
api1-1  | INFO:     Shutting down
api2-1  | INFO:     Waiting for application shutdown.
api2-1  | INFO:     Application shutdown complete.
api2-1  | INFO:     Finished server process [1]
api1-1  | INFO:     Waiting for application shutdown.
api1-1  | INFO:     Application shutdown complete.
api1-1  | INFO:     Finished server process [1]
[Kapi1-1 exited with code 0
[Kapi2-1 exited with code 0
